// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gj5NYy81bELgcxgFbeCA9LR6UU14pJc',
    appId: '1:141517695894:web:77b4446203c486db804bb7',
    messagingSenderId: '141517695894',
    projectId: 'flutter-project-1425',
    authDomain: 'flutter-project-1425.firebaseapp.com',
    databaseURL: 'https://flutter-project-1425-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-1425.appspot.com',
    measurementId: 'G-SGEXT22JQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiI_J8WP73BFuSJ6DWIHgCigWMbEVqAhk',
    appId: '1:141517695894:android:5b5b30c488bd5b1c804bb7',
    messagingSenderId: '141517695894',
    projectId: 'flutter-project-1425',
    databaseURL: 'https://flutter-project-1425-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-1425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1FOV52Xihq79cKOyu2nS5ROdOQRwQfUQ',
    appId: '1:141517695894:ios:7f78cfeb157e808a804bb7',
    messagingSenderId: '141517695894',
    projectId: 'flutter-project-1425',
    databaseURL: 'https://flutter-project-1425-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-1425.appspot.com',
    androidClientId: '141517695894-4npfl7hnt3k7p0pcfohpfvmvm24cts11.apps.googleusercontent.com',
    iosClientId: '141517695894-s3oa9mqhf9ldb6iqjbvo8g3869cdckr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
